import { Emotions } from "@utils/constants";

export const EntityConfig = {
    DEFAULT_EMOTION: Emotions.HAPPY,
    DEFAULT_HUNGER_POINTS: 100,
    DEFAULT_HEALTH_POINTS: 100,
    GOOD_HUNGER_VALUE: 80,
    GOOD_HEALTH_VALUE: 80,
    MAX_POINTS_VALUE: 100,
    MIN_GOOD_HEALTH_POINTS_VALUE: 20,
    HEALTH_LOOSE_SPEED: 10,
    REGENERATION_SPEED: 10,
    DYING_SPEED: 1,
    STARVING_SPEED: 10,
    LIVING_INTERVAL: 1000,
}